namespace QLBH.Controls.Cửa_hàng
{
    partial class c03_nv_cua_hang_v2
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            DevExpress.XtraEditors.TileItemElement tileItemElement1 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement2 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame1 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement3 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement4 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement5 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement6 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame2 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement7 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement8 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement13 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement14 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame4 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement15 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement16 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement17 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement18 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame5 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement19 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement20 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement21 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement22 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame6 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement23 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement24 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement35 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement36 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame9 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement37 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement38 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement27 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement28 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame7 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement29 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement30 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement31 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement32 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame8 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement33 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement34 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement39 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement9 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement10 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame3 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement11 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement12 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement25 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement26 = new DevExpress.XtraEditors.TileItemElement();
            this.m_tile_nghiep_vu = new DevExpress.XtraEditors.TileControl();
            this.m_tile_danh_muc = new DevExpress.XtraEditors.TileGroup();
            this.m_tile_dm_hang_hoa = new DevExpress.XtraEditors.TileItem();
            this.m_tile_nha_cung_cap = new DevExpress.XtraEditors.TileItem();
            this.m_tile_grp_hoa_don = new DevExpress.XtraEditors.TileGroup();
            this.m_tile_tra_cuu_hoa_don = new DevExpress.XtraEditors.TileItem();
            this.m_tile_thong_tin_phieu_nhap = new DevExpress.XtraEditors.TileItem();
            this.m_tile_tao_khuyen_mai = new DevExpress.XtraEditors.TileItem();
            this.m_tile_gia_excel = new DevExpress.XtraEditors.TileItem();
            this.m_tile_grp_phieu_nhap = new DevExpress.XtraEditors.TileGroup();
            this.m_tile_them_hang_hoa = new DevExpress.XtraEditors.TileItem();
            this.m_tile_nhap_kho = new DevExpress.XtraEditors.TileItem();
            this.tileItem6 = new DevExpress.XtraEditors.TileItem();
            this.m_tile_khach_hang = new DevExpress.XtraEditors.TileItem();
            this.m_tile_gia = new DevExpress.XtraEditors.TileItem();
            this.SuspendLayout();
            // 
            // m_tile_nghiep_vu
            // 
            this.m_tile_nghiep_vu.AppearanceGroupHighlighting.HoveredMaskColor = System.Drawing.Color.DimGray;
            this.m_tile_nghiep_vu.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            this.m_tile_nghiep_vu.AppearanceItem.Normal.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.ForwardDiagonal;
            this.m_tile_nghiep_vu.AppearanceItem.Normal.Options.UseBackColor = true;
            this.m_tile_nghiep_vu.BackColor = System.Drawing.Color.White;
            this.m_tile_nghiep_vu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_tile_nghiep_vu.DragSize = new System.Drawing.Size(0, 0);
            this.m_tile_nghiep_vu.Groups.Add(this.m_tile_danh_muc);
            this.m_tile_nghiep_vu.Groups.Add(this.m_tile_grp_hoa_don);
            this.m_tile_nghiep_vu.Groups.Add(this.m_tile_grp_phieu_nhap);
            this.m_tile_nghiep_vu.Location = new System.Drawing.Point(0, 0);
            this.m_tile_nghiep_vu.MaxId = 33;
            this.m_tile_nghiep_vu.Name = "m_tile_nghiep_vu";
            this.m_tile_nghiep_vu.Size = new System.Drawing.Size(1210, 567);
            this.m_tile_nghiep_vu.TabIndex = 3;
            this.m_tile_nghiep_vu.Text = "tileControl3";
            // 
            // m_tile_danh_muc
            // 
            this.m_tile_danh_muc.Items.Add(this.m_tile_dm_hang_hoa);
            this.m_tile_danh_muc.Items.Add(this.m_tile_nha_cung_cap);
            this.m_tile_danh_muc.Items.Add(this.m_tile_khach_hang);
            this.m_tile_danh_muc.Name = "m_tile_danh_muc";
            this.m_tile_danh_muc.Text = "tileGroup1";
            // 
            // m_tile_dm_hang_hoa
            // 
            this.m_tile_dm_hang_hoa.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_dm_hang_hoa.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement1.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement1.Appearance.Hovered.Options.UseFont = true;
            tileItemElement1.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement1.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement1.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement1.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement1.Appearance.Normal.Options.UseFont = true;
            tileItemElement1.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement1.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement1.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement1.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement1.Appearance.Selected.Options.UseFont = true;
            tileItemElement1.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement1.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement1.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement1.Text = "Hàng hóa";
            tileItemElement1.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement1.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement2.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement2.Appearance.Hovered.Options.UseFont = true;
            tileItemElement2.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement2.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement2.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement2.Appearance.Normal.Options.UseFont = true;
            tileItemElement2.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement2.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement2.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement2.Appearance.Selected.Options.UseFont = true;
            tileItemElement2.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement2.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement2.Text = "Quản lý danh mục hàng hóa";
            tileItemElement2.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement2.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_dm_hang_hoa.Elements.Add(tileItemElement1);
            this.m_tile_dm_hang_hoa.Elements.Add(tileItemElement2);
            this.m_tile_dm_hang_hoa.FrameAnimationInterval = 200000;
            tileItemFrame1.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement3.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement3.Appearance.Hovered.Options.UseFont = true;
            tileItemElement3.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement3.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement3.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement3.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement3.Appearance.Normal.Options.UseFont = true;
            tileItemElement3.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement3.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement3.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement3.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement3.Appearance.Selected.Options.UseFont = true;
            tileItemElement3.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement3.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement3.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement3.Text = "Hàng hóa";
            tileItemElement3.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement3.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement4.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement4.Appearance.Hovered.Options.UseFont = true;
            tileItemElement4.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement4.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement4.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement4.Appearance.Normal.Options.UseFont = true;
            tileItemElement4.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement4.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement4.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement4.Appearance.Selected.Options.UseFont = true;
            tileItemElement4.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement4.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement4.Text = "Quản lý danh mục hàng hóa";
            tileItemElement4.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement4.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame1.Elements.Add(tileItemElement3);
            tileItemFrame1.Elements.Add(tileItemElement4);
            this.m_tile_dm_hang_hoa.Frames.Add(tileItemFrame1);
            this.m_tile_dm_hang_hoa.Id = 28;
            this.m_tile_dm_hang_hoa.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_dm_hang_hoa.Name = "m_tile_dm_hang_hoa";
            // 
            // m_tile_nha_cung_cap
            // 
            this.m_tile_nha_cung_cap.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_nha_cung_cap.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement5.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement5.Appearance.Hovered.Options.UseFont = true;
            tileItemElement5.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement5.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement5.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement5.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement5.Appearance.Normal.Options.UseFont = true;
            tileItemElement5.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement5.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement5.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement5.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement5.Appearance.Selected.Options.UseFont = true;
            tileItemElement5.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement5.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement5.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement5.Text = "Nhà cung cấp";
            tileItemElement5.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement5.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement6.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement6.Appearance.Hovered.Options.UseFont = true;
            tileItemElement6.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement6.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement6.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement6.Appearance.Normal.Options.UseFont = true;
            tileItemElement6.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement6.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement6.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement6.Appearance.Selected.Options.UseFont = true;
            tileItemElement6.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement6.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement6.Text = "Quản lý danh mục nhà cung cấp";
            tileItemElement6.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement6.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_nha_cung_cap.Elements.Add(tileItemElement5);
            this.m_tile_nha_cung_cap.Elements.Add(tileItemElement6);
            this.m_tile_nha_cung_cap.FrameAnimationInterval = 200000;
            tileItemFrame2.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement7.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement7.Appearance.Hovered.Options.UseFont = true;
            tileItemElement7.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement7.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement7.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement7.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement7.Appearance.Normal.Options.UseFont = true;
            tileItemElement7.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement7.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement7.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement7.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement7.Appearance.Selected.Options.UseFont = true;
            tileItemElement7.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement7.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement7.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement7.Text = "Nhà cung cấp";
            tileItemElement7.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement7.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement8.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement8.Appearance.Hovered.Options.UseFont = true;
            tileItemElement8.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement8.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement8.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement8.Appearance.Normal.Options.UseFont = true;
            tileItemElement8.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement8.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement8.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement8.Appearance.Selected.Options.UseFont = true;
            tileItemElement8.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement8.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement8.Text = "Quản lý danh mục nhà cung cấp";
            tileItemElement8.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement8.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame2.Elements.Add(tileItemElement7);
            tileItemFrame2.Elements.Add(tileItemElement8);
            this.m_tile_nha_cung_cap.Frames.Add(tileItemFrame2);
            this.m_tile_nha_cung_cap.Id = 29;
            this.m_tile_nha_cung_cap.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_nha_cung_cap.Name = "m_tile_nha_cung_cap";
            // 
            // m_tile_grp_hoa_don
            // 
            this.m_tile_grp_hoa_don.Items.Add(this.m_tile_tra_cuu_hoa_don);
            this.m_tile_grp_hoa_don.Items.Add(this.m_tile_thong_tin_phieu_nhap);
            this.m_tile_grp_hoa_don.Items.Add(this.m_tile_tao_khuyen_mai);
            this.m_tile_grp_hoa_don.Items.Add(this.m_tile_gia);
            this.m_tile_grp_hoa_don.Name = "m_tile_grp_hoa_don";
            // 
            // m_tile_tra_cuu_hoa_don
            // 
            this.m_tile_tra_cuu_hoa_don.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_tra_cuu_hoa_don.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement13.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement13.Appearance.Hovered.Options.UseFont = true;
            tileItemElement13.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement13.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement13.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement13.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement13.Appearance.Normal.Options.UseFont = true;
            tileItemElement13.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement13.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement13.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement13.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement13.Appearance.Selected.Options.UseFont = true;
            tileItemElement13.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement13.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement13.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement13.Text = "Quản lý hóa đơn";
            tileItemElement13.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement13.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement14.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement14.Appearance.Hovered.Options.UseFont = true;
            tileItemElement14.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement14.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement14.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement14.Appearance.Normal.Options.UseFont = true;
            tileItemElement14.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement14.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement14.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement14.Appearance.Selected.Options.UseFont = true;
            tileItemElement14.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement14.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement14.Text = "Tra cứu, sửa, xóa thông tin hóa đơn";
            tileItemElement14.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement14.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_tra_cuu_hoa_don.Elements.Add(tileItemElement13);
            this.m_tile_tra_cuu_hoa_don.Elements.Add(tileItemElement14);
            this.m_tile_tra_cuu_hoa_don.FrameAnimationInterval = 200000;
            tileItemFrame4.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement15.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement15.Appearance.Hovered.Options.UseFont = true;
            tileItemElement15.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement15.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement15.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement15.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement15.Appearance.Normal.Options.UseFont = true;
            tileItemElement15.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement15.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement15.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement15.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement15.Appearance.Selected.Options.UseFont = true;
            tileItemElement15.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement15.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement15.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement15.Text = "Quản lý hóa đơn";
            tileItemElement15.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement15.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement16.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement16.Appearance.Hovered.Options.UseFont = true;
            tileItemElement16.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement16.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement16.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement16.Appearance.Normal.Options.UseFont = true;
            tileItemElement16.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement16.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement16.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement16.Appearance.Selected.Options.UseFont = true;
            tileItemElement16.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement16.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement16.Text = "Tra cứu, sửa, xóa thông tin hóa đơn";
            tileItemElement16.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement16.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame4.Elements.Add(tileItemElement15);
            tileItemFrame4.Elements.Add(tileItemElement16);
            this.m_tile_tra_cuu_hoa_don.Frames.Add(tileItemFrame4);
            this.m_tile_tra_cuu_hoa_don.Id = 10;
            this.m_tile_tra_cuu_hoa_don.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_tra_cuu_hoa_don.Name = "m_tile_tra_cuu_hoa_don";
            // 
            // m_tile_thong_tin_phieu_nhap
            // 
            this.m_tile_thong_tin_phieu_nhap.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_thong_tin_phieu_nhap.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement17.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement17.Appearance.Hovered.Options.UseFont = true;
            tileItemElement17.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement17.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement17.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement17.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement17.Appearance.Normal.Options.UseFont = true;
            tileItemElement17.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement17.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement17.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement17.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement17.Appearance.Selected.Options.UseFont = true;
            tileItemElement17.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement17.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement17.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement17.Text = "Quản lý phiếu nhập";
            tileItemElement17.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement17.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement18.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement18.Appearance.Hovered.Options.UseFont = true;
            tileItemElement18.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement18.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement18.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement18.Appearance.Normal.Options.UseFont = true;
            tileItemElement18.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement18.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement18.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement18.Appearance.Selected.Options.UseFont = true;
            tileItemElement18.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement18.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement18.Text = "Thêm sửa xóa phiếu nhập";
            tileItemElement18.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement18.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_thong_tin_phieu_nhap.Elements.Add(tileItemElement17);
            this.m_tile_thong_tin_phieu_nhap.Elements.Add(tileItemElement18);
            this.m_tile_thong_tin_phieu_nhap.FrameAnimationInterval = 200000;
            tileItemFrame5.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement19.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement19.Appearance.Hovered.Options.UseFont = true;
            tileItemElement19.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement19.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement19.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement19.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement19.Appearance.Normal.Options.UseFont = true;
            tileItemElement19.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement19.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement19.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement19.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement19.Appearance.Selected.Options.UseFont = true;
            tileItemElement19.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement19.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement19.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement19.Text = "Quản lý phiếu nhập";
            tileItemElement19.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement19.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement20.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement20.Appearance.Hovered.Options.UseFont = true;
            tileItemElement20.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement20.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement20.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement20.Appearance.Normal.Options.UseFont = true;
            tileItemElement20.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement20.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement20.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement20.Appearance.Selected.Options.UseFont = true;
            tileItemElement20.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement20.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement20.Text = "Thêm sửa xóa phiếu nhập";
            tileItemElement20.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement20.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame5.Elements.Add(tileItemElement19);
            tileItemFrame5.Elements.Add(tileItemElement20);
            this.m_tile_thong_tin_phieu_nhap.Frames.Add(tileItemFrame5);
            this.m_tile_thong_tin_phieu_nhap.Id = 27;
            this.m_tile_thong_tin_phieu_nhap.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_thong_tin_phieu_nhap.Name = "m_tile_thong_tin_phieu_nhap";
            // 
            // m_tile_tao_khuyen_mai
            // 
            this.m_tile_tao_khuyen_mai.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_tao_khuyen_mai.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement21.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement21.Appearance.Hovered.Options.UseFont = true;
            tileItemElement21.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement21.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement21.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement21.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement21.Appearance.Normal.Options.UseFont = true;
            tileItemElement21.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement21.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement21.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement21.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement21.Appearance.Selected.Options.UseFont = true;
            tileItemElement21.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement21.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement21.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement21.Text = "Khuyến mãi";
            tileItemElement21.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement21.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement22.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement22.Appearance.Hovered.Options.UseFont = true;
            tileItemElement22.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement22.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement22.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement22.Appearance.Normal.Options.UseFont = true;
            tileItemElement22.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement22.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement22.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement22.Appearance.Selected.Options.UseFont = true;
            tileItemElement22.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement22.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement22.Text = "Thêm sửa xóa đợt khuyến mãi và các hàng hóa áp dụng";
            tileItemElement22.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement22.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_tao_khuyen_mai.Elements.Add(tileItemElement21);
            this.m_tile_tao_khuyen_mai.Elements.Add(tileItemElement22);
            this.m_tile_tao_khuyen_mai.FrameAnimationInterval = 200000;
            tileItemFrame6.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement23.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement23.Appearance.Hovered.Options.UseFont = true;
            tileItemElement23.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement23.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement23.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement23.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement23.Appearance.Normal.Options.UseFont = true;
            tileItemElement23.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement23.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement23.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement23.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement23.Appearance.Selected.Options.UseFont = true;
            tileItemElement23.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement23.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement23.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement23.Text = "Khuyến mãi";
            tileItemElement23.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopLeft;
            tileItemElement23.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement24.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement24.Appearance.Hovered.Options.UseFont = true;
            tileItemElement24.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement24.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement24.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement24.Appearance.Normal.Options.UseFont = true;
            tileItemElement24.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement24.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement24.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement24.Appearance.Selected.Options.UseFont = true;
            tileItemElement24.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement24.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement24.Text = "Thêm sửa xóa đợt khuyến mãi và các hàng hóa áp dụng";
            tileItemElement24.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement24.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame6.Elements.Add(tileItemElement23);
            tileItemFrame6.Elements.Add(tileItemElement24);
            this.m_tile_tao_khuyen_mai.Frames.Add(tileItemFrame6);
            this.m_tile_tao_khuyen_mai.Id = 18;
            this.m_tile_tao_khuyen_mai.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_tao_khuyen_mai.Name = "m_tile_tao_khuyen_mai";
            // 
            // m_tile_gia_excel
            // 
            this.m_tile_gia_excel.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_gia_excel.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement35.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement35.Appearance.Hovered.Options.UseFont = true;
            tileItemElement35.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement35.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement35.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement35.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement35.Appearance.Normal.Options.UseFont = true;
            tileItemElement35.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement35.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement35.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement35.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement35.Appearance.Selected.Options.UseFont = true;
            tileItemElement35.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement35.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement35.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement35.Text = "Điều chỉnh giá";
            tileItemElement35.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement35.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement36.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement36.Appearance.Hovered.Options.UseFont = true;
            tileItemElement36.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement36.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement36.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement36.Appearance.Normal.Options.UseFont = true;
            tileItemElement36.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement36.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement36.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement36.Appearance.Selected.Options.UseFont = true;
            tileItemElement36.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement36.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement36.Text = "Thay đổi giá sản phẩm với dữ liệu từ Excel";
            tileItemElement36.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement36.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_gia_excel.Elements.Add(tileItemElement35);
            this.m_tile_gia_excel.Elements.Add(tileItemElement36);
            this.m_tile_gia_excel.FrameAnimationInterval = 200000;
            tileItemFrame9.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement37.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement37.Appearance.Hovered.Options.UseFont = true;
            tileItemElement37.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement37.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement37.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement37.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement37.Appearance.Normal.Options.UseFont = true;
            tileItemElement37.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement37.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement37.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement37.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement37.Appearance.Selected.Options.UseFont = true;
            tileItemElement37.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement37.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement37.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement37.Text = "Điều chỉnh giá";
            tileItemElement37.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement37.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement38.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement38.Appearance.Hovered.Options.UseFont = true;
            tileItemElement38.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement38.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement38.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement38.Appearance.Normal.Options.UseFont = true;
            tileItemElement38.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement38.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement38.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement38.Appearance.Selected.Options.UseFont = true;
            tileItemElement38.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement38.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement38.Text = "Thay đổi giá sản phẩm với dữ liệu từ Excel";
            tileItemElement38.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement38.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame9.Elements.Add(tileItemElement37);
            tileItemFrame9.Elements.Add(tileItemElement38);
            this.m_tile_gia_excel.Frames.Add(tileItemFrame9);
            this.m_tile_gia_excel.Id = 25;
            this.m_tile_gia_excel.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_gia_excel.Name = "m_tile_gia_excel";
            // 
            // m_tile_grp_phieu_nhap
            // 
            this.m_tile_grp_phieu_nhap.Items.Add(this.m_tile_them_hang_hoa);
            this.m_tile_grp_phieu_nhap.Items.Add(this.m_tile_nhap_kho);
            this.m_tile_grp_phieu_nhap.Items.Add(this.m_tile_gia_excel);
            this.m_tile_grp_phieu_nhap.Name = "m_tile_grp_phieu_nhap";
            // 
            // m_tile_them_hang_hoa
            // 
            this.m_tile_them_hang_hoa.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_them_hang_hoa.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement27.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement27.Appearance.Hovered.Options.UseFont = true;
            tileItemElement27.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement27.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement27.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement27.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement27.Appearance.Normal.Options.UseFont = true;
            tileItemElement27.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement27.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement27.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement27.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement27.Appearance.Selected.Options.UseFont = true;
            tileItemElement27.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement27.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement27.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement27.Text = "Mặt hàng mới";
            tileItemElement27.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement27.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement28.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement28.Appearance.Hovered.Options.UseFont = true;
            tileItemElement28.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement28.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement28.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement28.Appearance.Normal.Options.UseFont = true;
            tileItemElement28.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement28.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement28.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement28.Appearance.Selected.Options.UseFont = true;
            tileItemElement28.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement28.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement28.Text = "Thêm mặt hàng mới từ file excel";
            tileItemElement28.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement28.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_them_hang_hoa.Elements.Add(tileItemElement27);
            this.m_tile_them_hang_hoa.Elements.Add(tileItemElement28);
            this.m_tile_them_hang_hoa.FrameAnimationInterval = 200000;
            tileItemFrame7.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement29.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement29.Appearance.Hovered.Options.UseFont = true;
            tileItemElement29.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement29.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement29.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement29.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement29.Appearance.Normal.Options.UseFont = true;
            tileItemElement29.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement29.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement29.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement29.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement29.Appearance.Selected.Options.UseFont = true;
            tileItemElement29.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement29.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement29.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement29.Text = "Mặt hàng mới";
            tileItemElement29.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement29.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement30.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement30.Appearance.Hovered.Options.UseFont = true;
            tileItemElement30.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement30.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement30.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement30.Appearance.Normal.Options.UseFont = true;
            tileItemElement30.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement30.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement30.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement30.Appearance.Selected.Options.UseFont = true;
            tileItemElement30.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement30.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement30.Text = "Thêm mặt hàng mới từ file excel";
            tileItemElement30.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement30.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame7.Elements.Add(tileItemElement29);
            tileItemFrame7.Elements.Add(tileItemElement30);
            this.m_tile_them_hang_hoa.Frames.Add(tileItemFrame7);
            this.m_tile_them_hang_hoa.Id = 24;
            this.m_tile_them_hang_hoa.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_them_hang_hoa.Name = "m_tile_them_hang_hoa";
            // 
            // m_tile_nhap_kho
            // 
            this.m_tile_nhap_kho.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_nhap_kho.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement31.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement31.Appearance.Hovered.Options.UseFont = true;
            tileItemElement31.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement31.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement31.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement31.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement31.Appearance.Normal.Options.UseFont = true;
            tileItemElement31.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement31.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement31.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement31.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement31.Appearance.Selected.Options.UseFont = true;
            tileItemElement31.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement31.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement31.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement31.Text = "Thêm phiếu nhập ";
            tileItemElement31.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement31.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement32.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement32.Appearance.Hovered.Options.UseFont = true;
            tileItemElement32.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement32.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement32.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement32.Appearance.Normal.Options.UseFont = true;
            tileItemElement32.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement32.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement32.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement32.Appearance.Selected.Options.UseFont = true;
            tileItemElement32.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement32.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement32.Text = "Thêm phiếu nhập từ file Excel mẫu";
            tileItemElement32.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement32.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_nhap_kho.Elements.Add(tileItemElement31);
            this.m_tile_nhap_kho.Elements.Add(tileItemElement32);
            this.m_tile_nhap_kho.FrameAnimationInterval = 200000;
            tileItemFrame8.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement33.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement33.Appearance.Hovered.Options.UseFont = true;
            tileItemElement33.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement33.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement33.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement33.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement33.Appearance.Normal.Options.UseFont = true;
            tileItemElement33.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement33.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement33.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement33.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement33.Appearance.Selected.Options.UseFont = true;
            tileItemElement33.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement33.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement33.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement33.Text = "Thêm phiếu nhập ";
            tileItemElement33.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement33.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement34.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement34.Appearance.Hovered.Options.UseFont = true;
            tileItemElement34.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement34.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement34.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement34.Appearance.Normal.Options.UseFont = true;
            tileItemElement34.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement34.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement34.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement34.Appearance.Selected.Options.UseFont = true;
            tileItemElement34.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement34.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement34.Text = "Thêm phiếu nhập từ file Excel mẫu";
            tileItemElement34.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement34.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame8.Elements.Add(tileItemElement33);
            tileItemFrame8.Elements.Add(tileItemElement34);
            this.m_tile_nhap_kho.Frames.Add(tileItemFrame8);
            this.m_tile_nhap_kho.Id = 16;
            this.m_tile_nhap_kho.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_nhap_kho.Name = "m_tile_nhap_kho";
            // 
            // tileItem6
            // 
            tileItemElement39.Text = "tileItem6";
            this.tileItem6.Elements.Add(tileItemElement39);
            this.tileItem6.Id = 30;
            this.tileItem6.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem6.Name = "tileItem6";
            // 
            // m_tile_khach_hang
            // 
            this.m_tile_khach_hang.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_khach_hang.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement9.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement9.Appearance.Hovered.Options.UseFont = true;
            tileItemElement9.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement9.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement9.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement9.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement9.Appearance.Normal.Options.UseFont = true;
            tileItemElement9.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement9.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement9.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement9.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement9.Appearance.Selected.Options.UseFont = true;
            tileItemElement9.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement9.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement9.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement9.Text = "Khách hàng";
            tileItemElement9.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement9.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement10.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement10.Appearance.Hovered.Options.UseFont = true;
            tileItemElement10.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement10.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement10.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement10.Appearance.Normal.Options.UseFont = true;
            tileItemElement10.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement10.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement10.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement10.Appearance.Selected.Options.UseFont = true;
            tileItemElement10.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement10.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement10.Text = "Quản lý danh mục khách hàng";
            tileItemElement10.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement10.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_khach_hang.Elements.Add(tileItemElement9);
            this.m_tile_khach_hang.Elements.Add(tileItemElement10);
            this.m_tile_khach_hang.FrameAnimationInterval = 200000;
            tileItemFrame3.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemElement11.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement11.Appearance.Hovered.Options.UseFont = true;
            tileItemElement11.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement11.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement11.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement11.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement11.Appearance.Normal.Options.UseFont = true;
            tileItemElement11.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement11.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement11.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement11.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement11.Appearance.Selected.Options.UseFont = true;
            tileItemElement11.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement11.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement11.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement11.Text = "Khách hàng";
            tileItemElement11.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement11.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement12.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement12.Appearance.Hovered.Options.UseFont = true;
            tileItemElement12.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement12.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement12.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement12.Appearance.Normal.Options.UseFont = true;
            tileItemElement12.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement12.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement12.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement12.Appearance.Selected.Options.UseFont = true;
            tileItemElement12.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement12.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement12.Text = "Quản lý danh mục khách hàng";
            tileItemElement12.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement12.TextLocation = new System.Drawing.Point(4, 40);
            tileItemFrame3.Elements.Add(tileItemElement11);
            tileItemFrame3.Elements.Add(tileItemElement12);
            this.m_tile_khach_hang.Frames.Add(tileItemFrame3);
            this.m_tile_khach_hang.Id = 31;
            this.m_tile_khach_hang.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_khach_hang.Name = "m_tile_khach_hang";
            // 
            // m_tile_gia
            // 
            this.m_tile_gia.AppearanceItem.Normal.BackColor = System.Drawing.Color.Green;
            this.m_tile_gia.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement25.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement25.Appearance.Hovered.Options.UseFont = true;
            tileItemElement25.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement25.Appearance.Hovered.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement25.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement25.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement25.Appearance.Normal.Options.UseFont = true;
            tileItemElement25.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement25.Appearance.Normal.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement25.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement25.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI Light", 17F);
            tileItemElement25.Appearance.Selected.Options.UseFont = true;
            tileItemElement25.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement25.Appearance.Selected.TextOptions.Trimming = DevExpress.Utils.Trimming.EllipsisCharacter;
            tileItemElement25.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.NoWrap;
            tileItemElement25.Text = "Quản lý giá";
            tileItemElement25.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement25.TextLocation = new System.Drawing.Point(4, 0);
            tileItemElement26.Appearance.Hovered.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement26.Appearance.Hovered.Options.UseFont = true;
            tileItemElement26.Appearance.Hovered.Options.UseTextOptions = true;
            tileItemElement26.Appearance.Hovered.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement26.Appearance.Normal.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement26.Appearance.Normal.Options.UseFont = true;
            tileItemElement26.Appearance.Normal.Options.UseTextOptions = true;
            tileItemElement26.Appearance.Normal.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement26.Appearance.Selected.Font = new System.Drawing.Font("Segoe UI", 9F);
            tileItemElement26.Appearance.Selected.Options.UseFont = true;
            tileItemElement26.Appearance.Selected.Options.UseTextOptions = true;
            tileItemElement26.Appearance.Selected.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            tileItemElement26.MaxWidth = 900;
            tileItemElement26.Text = "Quản lý thông tin giá sản phẩm";
            tileItemElement26.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.Manual;
            tileItemElement26.TextLocation = new System.Drawing.Point(4, 40);
            this.m_tile_gia.Elements.Add(tileItemElement25);
            this.m_tile_gia.Elements.Add(tileItemElement26);
            this.m_tile_gia.Id = 32;
            this.m_tile_gia.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.m_tile_gia.Name = "m_tile_gia";
            // 
            // c03_nv_cua_hang_v2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.m_tile_nghiep_vu);
            this.Name = "c03_nv_cua_hang_v2";
            this.Size = new System.Drawing.Size(1210, 567);
            this.ResumeLayout(false);

        }

        #endregion

        private DevExpress.XtraEditors.TileControl m_tile_nghiep_vu;
        private DevExpress.XtraEditors.TileGroup m_tile_danh_muc;
        private DevExpress.XtraEditors.TileItem m_tile_dm_hang_hoa;
        private DevExpress.XtraEditors.TileItem m_tile_nha_cung_cap;
        private DevExpress.XtraEditors.TileGroup m_tile_grp_hoa_don;
        private DevExpress.XtraEditors.TileItem m_tile_tra_cuu_hoa_don;
        private DevExpress.XtraEditors.TileItem m_tile_thong_tin_phieu_nhap;
        private DevExpress.XtraEditors.TileItem m_tile_tao_khuyen_mai;
        private DevExpress.XtraEditors.TileItem m_tile_gia_excel;
        private DevExpress.XtraEditors.TileGroup m_tile_grp_phieu_nhap;
        private DevExpress.XtraEditors.TileItem m_tile_them_hang_hoa;
        private DevExpress.XtraEditors.TileItem m_tile_nhap_kho;
        private DevExpress.XtraEditors.TileItem m_tile_khach_hang;
        private DevExpress.XtraEditors.TileItem tileItem6;
        private DevExpress.XtraEditors.TileItem m_tile_gia;
    }
}
