//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CUA_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_CUA_HANG()
        {
            this.DM_QUYEN_CHI_TIET = new HashSet<DM_QUYEN_CHI_TIET>();
            this.GD_HOA_DON = new HashSet<GD_HOA_DON>();
            this.GD_TON_KHO = new HashSet<GD_TON_KHO>();
            this.GD_PHIEU_NHAP_XUAT = new HashSet<GD_PHIEU_NHAP_XUAT>();
        }
    
        public decimal ID { get; set; }
        public string MA_CUA_HANG { get; set; }
        public string TEN_CUA_HANG { get; set; }
        public string DIA_CHI { get; set; }
        public string DA_XOA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_QUYEN_CHI_TIET> DM_QUYEN_CHI_TIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_HOA_DON> GD_HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_TON_KHO> GD_TON_KHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_PHIEU_NHAP_XUAT> GD_PHIEU_NHAP_XUAT { get; set; }
    }
}
