//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_KHACH_HANG
    {
        public decimal ID { get; set; }
        public decimal ID_TAI_KHOAN { get; set; }
        public string LIEN_LAC { get; set; }
        public string SO_DIEN_THOAI { get; set; }
        public System.DateTime NGAY_THAM_GIA { get; set; }
        public decimal DIEM { get; set; }
        public decimal TONG_TIEN_DA_MUA { get; set; }
    
        public virtual DM_TAI_KHOAN DM_TAI_KHOAN { get; set; }
    }
}
