//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NHA_CUNG_CAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_NHA_CUNG_CAP()
        {
            this.DM_HANG_HOA = new HashSet<DM_HANG_HOA>();
        }
    
        public decimal ID { get; set; }
        public string TEN_NHA_CUNG_CAP { get; set; }
        public string SO_DIEN_THOAI { get; set; }
        public string EMAIL { get; set; }
        public string DIA_CHI { get; set; }
        public string TEN_NGUOI_DAI_DIEN { get; set; }
        public string MA_NHA_CUNG_CAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_HANG_HOA> DM_HANG_HOA { get; set; }
    }
}
