//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_QUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_QUYEN()
        {
            this.DM_QUYEN_CHI_TIET = new HashSet<DM_QUYEN_CHI_TIET>();
        }
    
        public decimal ID { get; set; }
        public string MA_QUYEN { get; set; }
        public string TEN_QUYEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_QUYEN_CHI_TIET> DM_QUYEN_CHI_TIET { get; set; }
    }
}
