//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService3
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_KHUYEN_MAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GD_KHUYEN_MAI()
        {
            this.GD_KHUYEN_MAI_CHI_TIET = new HashSet<GD_KHUYEN_MAI_CHI_TIET>();
        }
    
        public decimal ID { get; set; }
        public string MA_DOT { get; set; }
        public string MO_TA { get; set; }
        public System.DateTime THOI_GIAN_BAT_DAU { get; set; }
        public System.DateTime THOI_GIAN_KET_THUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_KHUYEN_MAI_CHI_TIET> GD_KHUYEN_MAI_CHI_TIET { get; set; }
    }
}
