using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using LibraryApi;

namespace QLBH.Controls.Hàng_hóa
{
    public partial class c01_quan_ly_tag : UserControl
    {
        public c01_quan_ly_tag()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            
        }

        private void c01_quan_ly_tag_Load(object sender, EventArgs e)
        {
            QuanLyTagHangHoa.LayDanhSachTag(this, data =>
            {
                data_2_sle(data);
            });
        }

        private void data_2_sle(MyNetwork.TraVe<List<string>> data)
        {
            Common.CommonFunction.list_to_data_table(data.Data);
            //m_sle_Tag.Properties.DataSource = Common.CommonFunction.convert_list_2_data_table(data);
            //m_sle_Tag.Properties.DisplayMember = "TEN_HANG_HOA;
        }


    }
}
